name: Configure GitHub Pages

on:
  project:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Configure GitHub Pages      
        uses: actions/configure-pages@v5.0.0
